name: "AD Offensive Module - Recon Phase"

on:
  workflow_dispatch: # Permet de le lancer manuellement avec le bouton "Run workflow"
  repository_dispatch:
    types: [ad_scan_event] # Pour ton futur bouton sur ton Dashboard React

jobs:
  reconnaissance:
    # On utilise ton Runner Kali !
    runs-on: [self-hosted, kali]
    
    steps:
      - name: Vérifier la connectivité avec le DC
        run: ping -c 3 192.168.159.100

      - name: Scan de vulnérabilités (Nmap Scripts)
        run: |
          # Recherche de vulnérabilités SMB critiques
          nmap -sV -p 445 --script smb-vuln* 192.168.159.100 -oX ad_report.xml

      - name: Upload du rapport brut
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-AD-Nmap
          path: ad_report.xml
