name: "AD Offensive Module - Recon Phase (Black Box)"

on:
  workflow_dispatch: # Lancement manuel via le bouton "Run workflow"
  repository_dispatch:
    types: [ad_scan_event] # Pour ton futur bouton sur ton Dashboard React

jobs:
  reconnaissance:
    # Utilisation de ton runner Kali Linux local
    runs-on: [self-hosted, kali]
    
    steps:
      - name: 1. Vérification de la connectivité (Ping)
        run: |
          echo "Vérification de la route réseau vers le contrôleur de domaine..."
          ping -c 3 192.168.159.100

      - name: 2. Scan Nmap Anonyme (Énumération Sans Mot de Passe)
        run: |
          # Objectif : Extraire le maximum d'infos sans identifiants
          # -Pn : Ignore le blocage du ping par le pare-feu
          # -p 135,139,445 : Ports critiques RPC et SMB de l'Active Directory
          
          nmap -Pn -p 135,139,445 \
            --script smb-protocols,smb-os-discovery,smb-enum-shares,smb2-security-mode \
            192.168.159.100 -oX ad_report.xml

      - name: 3. Archivage du rapport XML pour analyse
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-AD-BlackBox
          path: ad_report.xml
