name: "AD Offensive Platform - Choix du Scan"

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Stratégie de scan'
        required: true
        default: 'anonyme'
        type: choice
        options:
          - anonyme
          - authentifie
      target_ip:
        description: 'IP cible'
        required: true
        default: '192.168.159.100'
      username:
        description: 'Utilisateur pour scan authentifié'
        required: false
        default: ''
      password:
        description: 'Mot de passe pour scan authentifié'
        required: false
        default: ''

jobs:
  offensive_task:
    runs-on: [self-hosted, kali]
    steps:
      - name: 1. Vérification réseau
        run: ping -c 2 ${{ github.event.inputs.target_ip }}

      # --- SCÉNARIO A : SCAN ANONYME ---
      - name: Lancer Scan Anonyme (Nmap + Enum4linux-ng basic)
        if: ${{ github.event.inputs.scan_type == 'anonyme' }}
        run: |
          # Utilisation de scripts NSE pour l'énumération profonde
          nmap -Pn -p 445,139,389 \
            --script smb-protocols,smb2-security-mode,smb-os-discovery,smb-enum-shares,ldap-rootdse \
            ${{ github.event.inputs.target_ip }} -oX ad_report.xml
          # On génère un format JSON pour que Llama puisse le lire facilement
          enum4linux-ng -A ${{ github.event.inputs.target_ip }} -j ad_report.json || true

      # --- SCÉNARIO B : SCAN AUTHENTIFIÉ (CHAINING) ---
      - name: Lancer Scan Authentifié (Enum4linux-ng)
        if: ${{ github.event.inputs.scan_type == 'authentifie' }}
        run: |
          # On utilise les credentials envoyés par le script Python
          USER="${{ github.event.inputs.username }}"
          if [ -z "$USER" ]; then USER="support.it"; fi
          
          PASS="${{ github.event.inputs.password }}"
          
          echo "🔥 Lancement de l'exploitation authentifiée avec l'utilisateur: $USER"
          
          # Exécution de enum4linux-ng avec les paramètres d'entrée
          enum4linux-ng -u "$USER" -p "$PASS" -w "PFE" -A ${{ github.event.inputs.target_ip }} -j ad_report.json || true

      - name: Archivage du rapport
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-ad
          path: ad_report.json
