name: "AD Offensive Platform - Choix du Scan"

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type de scan à réaliser'
        required: true
        default: 'anonyme'
        type: choice
        options:
          - anonyme
          - authentifie

jobs:
  offensive_task:
    runs-on: [self-hosted, kali]
    steps:
      - name: 1. Vérification réseau
        run: ping -c 2 192.168.159.100

      # --- SCÉNARIO A : SCAN ANONYME ---
      - name: Lancer Scan Anonyme
        if: ${{ github.event.inputs.scan_type == 'anonyme' }}
        run: |
          nmap -Pn -p 445 \
            --script smb-protocols,smb2-security-mode,smb-os-discovery \
            192.168.159.100 -oX ad_anonyme.xml

      # --- SCÉNARIO B : SCAN AUTHENTIFIÉ ---
      - name: Lancer Scan Authentifié
        if: ${{ github.event.inputs.scan_type == 'authentifie' }}
        env:
          USER: ${{ secrets.AD_USER }}
          PASS: ${{ secrets.AD_PASSWORD }}
        run: |
          nmap -Pn -p 445 \
            --script smb-enum-users,smb-enum-shares \
            --script-args "smbuser='${USER}',smbpass='${PASS}'" \
            192.168.159.100 -oX ad_authentifie.xml

      - name: Sauvegarder le rapport (selon le choix)
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-AD-${{ github.event.inputs.scan_type }}
          path: "*.xml"
