name: API Offensive Audit Pro

on:
  repository_dispatch:
    types: [newman_scan_event]

jobs:
  api-audit:
    runs-on: self-hosted
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Exécution du scan Newman (Mode Agressif)
        run: |
          # On injecte l'IP cible et on augmente le timeout à 30s (VM lente)
          # On ajoute --suppress-exit-code pour forcer la génération du JSON
          newman run "${{ github.event.client_payload.collection }}" \
          --env-var "host=192.168.159.131:8000" \
          --reporters cli,json \
          --reporter-json-export api_report.json \
          --timeout-request 30000 \
          --delay-request 500
        continue-on-error: true

      - name: 3. Archivage du rapport pour Llama 3
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-security-report
          path: api_report.json
          retention-days: 1
