name: "Audit Dynamique API avec Newman"

on:
  repository_dispatch:
    types: [newman_scan_event]

jobs:
  newman-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Execute Security Collection
        run: |
          newman run ${{ github.event.client_payload.collection }} \
          -r htmlextra --reporter-htmlextra-export report_api.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-Newman-API
          path: report_api.html
